typography_spectrum: 0.2686417228542268
color:
  brandStrength: 0.5367670345585793
  lightness: 0.8282752099912614
  saturation: 0.717455182923004
  rhythmicContrast: 0.9055048346053809
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
layout_spectrum: 0.4367902686353773
name: alpha lyrae
title: alpha lyrae
